defaults:
  - _self_
  - task: alphafold
  - representation: graph
  - model: ${representation}
  - training: pretrain
  - paths: default
  - optional best_model: ${task}_${representation}
  - pretrain: default
  - debug: null

seed: 0

# output directory, generated dynamically on each run
hydra:
  run:
    dir: outputs/pretrain/${task.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: outputs/pretrain/${task.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}